// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1757757374);
user_pref("browser.search.region", "ES");
user_pref("calendar.caldav.googleResync", 1757757374);
user_pref("calendar.list.sortOrder", "a2eca831-c9a6-48cb-b290-afb7c451a145");
user_pref("calendar.registry.a2eca831-c9a6-48cb-b290-afb7c451a145.calendar-main-default", true);
user_pref("calendar.registry.a2eca831-c9a6-48cb-b290-afb7c451a145.calendar-main-in-composite", true);
user_pref("calendar.registry.a2eca831-c9a6-48cb-b290-afb7c451a145.disabled", true);
user_pref("calendar.registry.a2eca831-c9a6-48cb-b290-afb7c451a145.name", "Casa");
user_pref("calendar.registry.a2eca831-c9a6-48cb-b290-afb7c451a145.type", "storage");
user_pref("calendar.registry.a2eca831-c9a6-48cb-b290-afb7c451a145.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Madrid");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.cache.lastUpdate", 1757757387);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.hasExperimentsInstalled", false);
user_pref("extensions.hasExtensionsInstalled", false);
user_pref("extensions.installedDistroAddon.langpack-es-ES@thunderbird.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20250723152110");
user_pref("extensions.lastAppVersion", "128.13.0");
user_pref("extensions.lastPlatformVersion", "128.13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"1d06c1c8-b7f8-45a8-a51a-e1da7cdff41b\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ui-rdf.version", 46);
user_pref("mailnews.database.global.datastore.id", "3794ee9a-1400-45d9-91ea-ef2ba6d7931");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "128.13.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1757757385);
user_pref("toolkit.telemetry.cachedClientID", "269bc7b7-cf84-4029-8d3f-4ab3e1287697");
user_pref("toolkit.telemetry.previousBuildID", "20250723152110");
